// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLzmHvvH19FKOgiqeREl-l6kDpmX9fuEY',
    appId: '1:1904691938:web:b34d9a942dcd802579acbb',
    messagingSenderId: '1904691938',
    projectId: 'chatapp-5db1c',
    authDomain: 'chatapp-5db1c.firebaseapp.com',
    storageBucket: 'chatapp-5db1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq8Q5FYc44NUv-rgPdt8pool0TzEOdhJs',
    appId: '1:1904691938:android:17ecc09431a2572279acbb',
    messagingSenderId: '1904691938',
    projectId: 'chatapp-5db1c',
    storageBucket: 'chatapp-5db1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCTieN1x7v7mVK7_dy44OkCXErcYTJ1PA',
    appId: '1:1904691938:ios:3f5dbf644b982f0c79acbb',
    messagingSenderId: '1904691938',
    projectId: 'chatapp-5db1c',
    storageBucket: 'chatapp-5db1c.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCTieN1x7v7mVK7_dy44OkCXErcYTJ1PA',
    appId: '1:1904691938:ios:3f5dbf644b982f0c79acbb',
    messagingSenderId: '1904691938',
    projectId: 'chatapp-5db1c',
    storageBucket: 'chatapp-5db1c.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLzmHvvH19FKOgiqeREl-l6kDpmX9fuEY',
    appId: '1:1904691938:web:8aada057a245317679acbb',
    messagingSenderId: '1904691938',
    projectId: 'chatapp-5db1c',
    authDomain: 'chatapp-5db1c.firebaseapp.com',
    storageBucket: 'chatapp-5db1c.firebasestorage.app',
  );
}
